### ISSUE TITLE
Add README. explaining the project, attaching the required screen shots.

### ISSUE THREAD

**Issue by SohamDave08** [SohamDave08/CamRadar#1]
### It's a criminal detection and recognition project using the LBPH algorithm.

**datasetCreator.py:**
![Picture2](https://user-images.githubusercontent.com/51802431/94796140-f9598400-03fb-11eb-804c-11e364b6226a.png)
![Picture1](https://user-images.githubusercontent.com/51802431/94796151-feb6ce80-03fb-11eb-9680-28a00ce987b3.png)

**Face_train.py:**
![Picture3](https://user-images.githubusercontent.com/51802431/94796195-13936200-03fc-11eb-8bac-a9687d8bd280.png)

**Face_detect.py:**
![Picture4](https://user-images.githubusercontent.com/51802431/94796259-24dc6e80-03fc-11eb-8dbe-ad40bbc55e37.png)

**Comment by RajvirSingh1313** [comment]
Hello Can I help??

**Comment by SohamDave08** [comment]
Sure @RajvirSingh1313. Should I assign you this issue? Please confirm.
